### ISSUE TITLE
ARMv6 support

### ISSUE THREAD

**Issue by NelsonBrandao** [thx/resvg-js#231]
Hi, Is there any plan to support armv6?

This project would be a good replacement for converting SVG to PNG without puppeteer on the Raspberry pi zero

**Comment by yisibl** [comment]
Raspberry Pi Zero is too old, you can try to compile it yourself using `zig cc`.

https://www.leemeichin.com/posts/gettin-ziggy-with-it-pi-zero/#:~:text=**-,build%20and%20push,-Zig%20comes%20with

**Comment by NelsonBrandao** [comment]
I was able to `cargo install resvg` the main lib on the Pi Zero. That is why I created this issue, to see if we could get official support.

Will try to compile `resvg-js` on the Pi Zero

**Comment by NelsonBrandao** [comment]
I was trying to setup this repo on my Pi but `yarn install` can't install `@swc/core`. Not sure if this is another problem related with ARMv6, this time on swc side.

```sh
yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 13s 484ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 13s 707ms
➤ YN0000: ┌ Link step
➤ YN0007: │ @swc/core@npm:1.3.53 [c0754] must be built because it never has been before or the last one failed
➤ YN0009: │ @swc/core@npm:1.3.53 [c0754] couldn't be built successfully (exit code 129, logs can be found here: /tmp/xfs-9c34ecea/build.log)
➤ YN0000: └ Completed in 16s 451ms
➤ YN0000: Failed with errors in 45s 507ms
```

```sh
cat /tmp/xfs-9c34ecea/build.log
# This file contains the result of Yarn building a package (@swc/core@virtual:c0754d0947c87dd3aa2aa4a7216571ecf617b1efc6919e3c9a3be40955d92a4e78049e28a88b7dace7c117aca71a911ea4399a0565d7757b3941855c7b94f9f1#npm:1.3.53)
# Script name: postinstall

```

**Comment by yisibl** [comment]
If you're just building binary `.node` files, you don't need to install any other dependencies, just `@napi-rs/cli` and then `npm run build`.

**Comment by NelsonBrandao** [comment]
So I ran `rustc -vV` on the Pi Zero to get the correct target:

```sh
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: arm-unknown-linux-gnueabihf
release: 1.69.0
LLVM version: 15.0.7
```

Decided to trigger the build on the actual Pi Zero instead of trying to cross compile. This was done by running `npm run build -- --target arm-unknown-linux-gnueabihf`

The build didn't throw any errors:

```sh
{...}
Finished release [optimized] target(s) in 109m 08s
```

and a `resvgjs.linux-arm-gnueabihf.node` file was created.

I then replace the original `node_modules/@resvg/resvg-js-linux-arm-gnueabihf/resvgjs.linux-arm-gnueabihf.node` inside my project `node_modules` with my built version.

Unfortunately the node script still throws an error when executing

```sh
Illegal instruction
```

I'm I doing something wrong here?

Btw thanks guys for all the help so far, much appreciated.

**Comment by yisibl** [comment]
Sorry, but since the Raspberry Pi Zero is so old, I'm not going to support it and close this issue for now. If you figure out how to build it, feel free to share it here.
